repos:
  - repo: https://github.com/homebysix/pre-commit-macadmin
    rev: v1.22.0
    hooks:
      - id: check-autopkg-recipes
        args: ["--recipe-prefix=com.github.iancohn.", "--strict", "--"]
      - id: forbid-autopkg-overrides
      - id: forbid-autopkg-trust-info
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=100"]
        exclude: ^McmApiProcessors/McmApiLib/vendor/
      - id: check-ast
        exclude: ^McmApiProcessors/McmApiLib/vendor/
      - id: check-case-conflict
        exclude: ^McmApiProcessors/McmApiLib/vendor/
      - id: check-executables-have-shebangs
        exclude: ^McmApiProcessors/McmApiLib/vendor/
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
        exclude: ^McmApiProcessors/McmApiLib/vendor/
      - id: end-of-file-fixer
        exclude: ^McmApiProcessors/McmApiLib/vendor/
      - id: fix-byte-order-marker
        exclude: ^McmApiProcessors/McmApiLib/vendor/
      - id: mixed-line-ending
        exclude: ^McmApiProcessors/McmApiLib/vendor/
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
        exclude: ^McmApiProcessors/McmApiLib/vendor/
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.12.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort

  # For future consideration:
  # - repo: https://github.com/pycqa/flake8
  #   rev: 5.0.4
  #   hooks:
  #     - id: flake8
  # - repo: https://github.com/pycqa/pylint
  #   rev: v2.13.5
  #   hooks:
  #     - id: pylint
